version: "3.5"

services:

    ssh-tunnels:
        image: flaviostutz/ssh-jwt
        ports:
          - "2222:22"
        secrets:
        - rs-pub-key          
        environment:
         - LOG_LEVEL=debug
         - JWT_ALGORITHM=RS512
         - JWT_KEY_SECRET_NAME=rs-pub-key
         - ENABLE_REMOTE_FORWARDING=true
         - ENABLE_LOCAL_FORWARDING=true
         - ENABLE_PTY=true    

    whoami:
        image: containous/whoami
        ports:
            - 3389:80            
            - 8111:8111

secrets:
    rs-pub-key:
        file: ./test_rsa.pub